Repository Zoo-Goorm/Zoo-Front, pull requests merged in 2025-03, with the labels that each got.

#7 chore: 디자인 시스템 정의 (semantic/spacing/responsive)
  zoo-client/.eslintrc.cjs
  zoo-client/prettier.config.cjs
  zoo-client/src/app/page.tsx
  zoo-client/src/styles/tokens/colors.ts
  zoo-client/src/styles/tokens/index.ts
  zoo-client/src/styles/tokens/spacing.ts
  zoo-client/tailwind.config.ts
  zoo-client/tsconfig.json
Labels: 🔧 CHORE, ♻️ REFACTOR

#8 feat: badge component 구현
  zoo-client/src/app/components/common/badge/Badge.tsx
  zoo-client/src/app/components/index.ts
  zoo-client/src/styles/tokens/colors.ts
Labels: ✨ FEAT

#9 feat: tab component 구현
  zoo-client/src/app/components/common/tab/ArrowBox.tsx
  zoo-client/src/app/components/common/tab/FilterOption.tsx
  zoo-client/src/app/components/common/tab/Tab.tsx
  zoo-client/src/app/components/common/tab/TabDates.tsx
  zoo-client/src/app/components/common/tab/ToggleButton.tsx
  zoo-client/src/app/components/common/tab/arrow/LeftArrow.tsx
  zoo-client/src/app/components/common/tab/arrow/LightArrow.tsx
  zoo-client/src/app/components/index.ts
  zoo-client/src/app/page.tsx
  zoo-client/src/public/tab/filter-icon.svg
Labels: ✨ FEAT

#17 Feat: accordion component 구현
  zoo-client/src/app/page.tsx
  zoo-client/src/components/common/accordion/Accordion.tsx
  zoo-client/src/components/common/accordion/DateInfoAccordion.tsx
  zoo-client/src/components/common/accordion/DateInfoList.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/mock/date.ts
  zoo-client/src/public/accordion/arrow.svg
  zoo-client/src/public/accordion/dateinfo-arrow.svg
Labels: ✨ FEAT

#20 feat: button component 구현
  zoo-client/public/button/right-arrow.svg
  zoo-client/public/button/top-arrow.svg
  zoo-client/public/tab/filter-icon.svg
  zoo-client/src/components/common/badge/BadgeList.tsx
  zoo-client/src/components/common/button/ListButton.tsx
  zoo-client/src/components/common/button/LoginButton.tsx
  zoo-client/src/components/common/button/OblongButton.tsx
  zoo-client/src/components/common/button/TopButton.tsx
  zoo-client/src/components/common/button/icon/LoginIcon.tsx
  zoo-client/src/components/common/button/icon/RightArrow.tsx
  zoo-client/src/components/common/chip/ChipList.tsx
  zoo-client/src/components/common/session/ApplyButton.tsx
  zoo-client/src/components/common/session/Session.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/speaker/Speaker.tsx
  zoo-client/src/components/common/speaker/SpeakerList.tsx
  zoo-client/src/components/common/tab/FilterOption.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/styles/tokens/colors.ts
  zoo-client/tailwind.config.ts
Labels: ✨ FEAT

#21 feat: radio component 구현
  zoo-client/public/accordion/arrow.svg
  zoo-client/public/accordion/dateinfo-arrow.svg
  zoo-client/public/radio/thumbnail.svg
  zoo-client/src/app/page.tsx
  zoo-client/src/components/common/accordion/Accordion.tsx
  zoo-client/src/components/common/accordion/DateInfoAccordion.tsx
  zoo-client/src/components/common/radio/Radio.tsx
  zoo-client/src/components/index.ts
Labels: ✨ FEAT

#22 feat: progressbar component 구현
  zoo-client/src/app/page.tsx
  zoo-client/src/components/common/progressbar/ProgressBar.tsx
  zoo-client/src/components/index.ts
Labels: ✨ FEAT

#24 feat: 로그인 페이지 UI 구현
  zoo-client/src/app/globals.css
  zoo-client/src/app/login/page.tsx
  zoo-client/src/components/common/button/LoginButton.tsx
  zoo-client/src/components/common/navigationBar/NavigationBar.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/constants/messages.ts
Labels: ✨ FEAT

#26 Feat: session schedule page 구현
  zoo-client/src/app/layout.tsx
  zoo-client/src/app/session-schedule/page.tsx
  zoo-client/src/components/common/accordion/Accordion.tsx
  zoo-client/src/components/common/button/ListButton.tsx
  zoo-client/src/components/common/button/PurchaseButton.tsx
  zoo-client/src/components/common/chip/ChipList.tsx
  zoo-client/src/components/common/session/ApplyButton.tsx
  zoo-client/src/components/common/session/Session.tsx
  zoo-client/src/components/common/session/SessionContainer.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/session/SessionList.tsx
  zoo-client/src/components/common/session/SessionTime.tsx
  zoo-client/src/components/common/speaker/Speaker.tsx
  zoo-client/src/components/common/speaker/SpeakerList.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/common/tab/TabDates.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/constants/session.ts
  zoo-client/src/mock/chip.ts
  zoo-client/src/mock/session.ts
  zoo-client/src/mock/speaker.ts
  zoo-client/src/store/useSessionStore.ts
  zoo-client/src/types/session/session.ts
  zoo-client/src/types/speaker/speaker.ts
Labels: ✨ FEAT

#28 feat: session apply UI 구현
  zoo-client/public/mock/speaker-img.svg
  zoo-client/src/app/session-apply/page.tsx
  zoo-client/src/app/session-schedule/page.tsx
  zoo-client/src/components/common/accordion/Accordion.tsx
  zoo-client/src/components/common/accordion/DateInfoAccordion.tsx
  zoo-client/src/components/common/accordion/DateInfoList.tsx
  zoo-client/src/components/common/badge/Badge.tsx
  zoo-client/src/components/common/button/ListButton.tsx
  zoo-client/src/components/common/button/PaymentButton.tsx
  zoo-client/src/components/common/button/SelectSessionButton.tsx
  zoo-client/src/components/common/progressbar/ProgressBar.tsx
  zoo-client/src/components/common/radio/Radio.tsx
  zoo-client/src/components/common/session/Session.tsx
  zoo-client/src/components/common/session/SessionContainer.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/session/SessionList.tsx
  zoo-client/src/components/common/session/SessionTime.tsx
  zoo-client/src/components/common/session/card/SessionCard.tsx
  zoo-client/src/components/common/session/card/SessionCardItem.tsx
  zoo-client/src/components/common/session/card/SessionCarousel.tsx
  zoo-client/src/components/common/session/card/arrow/LeftArrow.tsx
  zoo-client/src/components/common/session/card/arrow/LightArrow.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/constants/messages.ts
  zoo-client/src/constants/session.ts
  zoo-client/src/mock/badge.ts
  zoo-client/src/mock/date.ts
  zoo-client/src/mock/session.ts
  zoo-client/src/mock/speaker.ts
  zoo-client/src/store/useRadioStore.ts
  zoo-client/src/store/useSessionStore.ts
  zoo-client/src/types/session/session.ts
Labels: ✨ FEAT, 💄 DESIGN

#33 feat: 세션 결제 페이지 UI 구현
  zoo-client/package.json
  zoo-client/public/button/paymentIcon.png
  zoo-client/public/button/right-arrow.svg
  zoo-client/public/chip/xbox.svg
  zoo-client/public/jobItem/right-arrow.svg
  zoo-client/public/modal/close.svg
  zoo-client/src/app/conference/register/page.tsx
  zoo-client/src/app/globals.css
  zoo-client/src/components/common/button/OblongButton.tsx
  zoo-client/src/components/common/button/RegisterPaymentButton.tsx
  zoo-client/src/components/common/card/CardContent.tsx
  zoo-client/src/components/common/checkbox/CheckBox.tsx
  zoo-client/src/components/common/checkbox/CheckIcon.tsx
  zoo-client/src/components/common/chip/Chip.tsx
  zoo-client/src/components/common/chip/ChipList.tsx
  zoo-client/src/components/common/footer/Footer.tsx
  zoo-client/src/components/common/jobItem/JobItem.tsx
  zoo-client/src/components/common/modal/AlertModal.tsx
  zoo-client/src/components/common/modal/InterestModal.tsx
  zoo-client/src/components/common/modal/JobModal.tsx
  zoo-client/src/components/common/modal/Layout/ModalButton.tsx
  zoo-client/src/components/common/modal/Layout/ModalContainer.tsx
  zoo-client/src/components/common/modal/Layout/ModalHeader.tsx
  zoo-client/src/components/common/modal/Layout/Overlay.tsx
  zoo-client/src/components/common/navigationBar/NavigationBar.tsx
  zoo-client/src/components/common/session/SessionContainer.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/speaker/Speaker.tsx
  zoo-client/src/components/common/textField/TextField.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/register/RegisterButton.tsx
  zoo-client/src/components/register/RegisterForm.tsx
  zoo-client/src/constants/messages.ts
  zoo-client/src/constants/register.ts
  zoo-client/src/store/common/useChipStore.ts
  zoo-client/src/store/common/useModalStore.ts
  zoo-client/src/store/modal/useInterestItemStore.ts
  zoo-client/src/store/modal/useJobItemStore.ts
  zoo-client/src/styles/tokens/colors.ts
  zoo-client/src/types/modal/modal.ts
  zoo-client/tailwind.config.ts
  zoo-client/yarn.lock
Labels: ✨ FEAT

#35 feat: session page modal 구현
  zoo-client/public/button/close.svg
  zoo-client/src/app/session-apply/page.tsx
  zoo-client/src/app/session-schedule/@modal/[id]/page.tsx
  zoo-client/src/app/session-schedule/@modal/default.tsx
  zoo-client/src/app/session-schedule/[id]/page.tsx
  zoo-client/src/app/session-schedule/layout.tsx
  zoo-client/src/app/session-schedule/page.tsx
  zoo-client/src/components/common/accordion/DateInfoAccordion.tsx
  zoo-client/src/components/common/accordion/DateInfoList.tsx
  zoo-client/src/components/common/badge/Badge.tsx
  zoo-client/src/components/common/badge/BadgeList.tsx
  zoo-client/src/components/common/badge/CardBadge.tsx
  zoo-client/src/components/common/badge/ContentBadge.tsx
  zoo-client/src/components/common/button/ListButton.tsx
  zoo-client/src/components/common/button/PurchaseButton.tsx
  zoo-client/src/components/common/button/SelectSessionButton.tsx
  zoo-client/src/components/common/modal/SessionApplyModal.tsx
  zoo-client/src/components/common/modal/SessionDetailModal.tsx
  zoo-client/src/components/common/progressbar/ProgressBar.tsx
  zoo-client/src/components/common/radio/Radio.tsx
  zoo-client/src/components/common/radio/RadioContent.tsx
  zoo-client/src/components/common/session/ApplyButton.tsx
  zoo-client/src/components/common/session/Session.tsx
  zoo-client/src/components/common/session/SessionContainer.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/session/SessionList.tsx
  zoo-client/src/components/common/session/SessionTime.tsx
  zoo-client/src/components/common/session/card/SessionCard.tsx
  zoo-client/src/components/common/session/card/SessionCardItem.tsx
  zoo-client/src/components/common/session/card/SessionCarousel.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/common/tab/TabDates.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/constants/messages.ts
  zoo-client/src/hook/useDetailAccess.tsx
  zoo-client/src/hook/useFilterSessionData.tsx
  zoo-client/src/hook/useTitleAccess.tsx
  zoo-client/src/mock/activeStates.ts
  zoo-client/src/mock/badge.ts
  zoo-client/src/mock/chip.ts
  zoo-client/src/mock/session.ts
  zoo-client/src/mock/sessionsDetailed.ts
  zoo-client/src/mock/ticket.ts
  zoo-client/src/store/common/useApplyStore.ts
  zoo-client/src/store/common/useRadioStore.ts
  zoo-client/src/store/common/useSessionStore.ts
  zoo-client/src/store/useSessionStore.ts
  zoo-client/src/types/badge/Badge.ts
  zoo-client/src/types/session/session.ts
  zoo-client/src/types/ticket/ticket.ts
Labels: ✨ FEAT

#38 Feat: session api 연결
  zoo-client/next.config.ts
  zoo-client/src/actions/session.ts
  zoo-client/src/app/services/api.ts
  zoo-client/src/app/services/session.ts
  zoo-client/src/app/session-apply/page.tsx
  zoo-client/src/app/session-schedule/@modal/[id]/page.tsx
  zoo-client/src/app/session-schedule/page.tsx
  zoo-client/src/components/common/button/ListButton.tsx
  zoo-client/src/components/common/card/CardContent.tsx
  zoo-client/src/components/common/modal/SessionApplyModal.tsx
  zoo-client/src/components/common/modal/SessionDetailModal.tsx
  zoo-client/src/components/common/radio/Radio.tsx
  zoo-client/src/components/common/session/Session.tsx
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/session/SessionTime.tsx
  zoo-client/src/components/common/session/card/SessionCardItem.tsx
  zoo-client/src/components/common/speaker/Speaker.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/common/tab/ToggleButton.tsx
  zoo-client/src/hook/useDetailAccess.tsx
  zoo-client/src/mock/sessionsDetailed.ts
  zoo-client/src/mock/ticket.ts
  zoo-client/src/store/common/useApplyStore.ts
  zoo-client/src/store/common/useSessionStore.ts
  zoo-client/src/store/common/useToggleStore.ts
  zoo-client/src/types/session/session.ts
  zoo-client/src/types/ticket/ticket.ts
Labels: ✨ FEAT

#40 feat: 비회원 페이지 UI 구현
  zoo-client/next.config.ts
  zoo-client/src/apis/index.ts
  zoo-client/src/app/login/page.tsx
  zoo-client/src/app/none-member/page.tsx
  zoo-client/src/components/common/button/LoginButton.tsx
  zoo-client/src/components/common/button/OblongButton.tsx
  zoo-client/src/components/common/textField/TextField.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/noneMember/NoneMemberForm.tsx
Labels: ✨ FEAT

#43 fix: build 에러 해결
  zoo-client/src/components/common/session/SessionContent.tsx
  zoo-client/src/components/common/session/card/SessionCardItem.tsx
  zoo-client/src/types/session/session.ts
Labels: 🔨 FIX, 🌎 DEPLOY

#45 Feat: Insight infomation UI 구현
  zoo-client/public/button/down-arrow.svg
  zoo-client/public/button/heart-fill.svg
  zoo-client/public/button/up-arrow.svg
  zoo-client/public/mock/profile.svg
  zoo-client/public/mock/reply-icon.svg
  zoo-client/public/social/github.svg
  zoo-client/public/social/instagram.svg
  zoo-client/public/social/linkedin.svg
  zoo-client/public/social/notion.svg
  zoo-client/public/social/threads.svg
  zoo-client/src/app/insight/[id]/page.tsx
  zoo-client/src/app/insight/page.tsx
  zoo-client/src/app/layout.tsx
  zoo-client/src/app/session-schedule/@modal/[id]/page.tsx
  zoo-client/src/app/session-schedule/@modal/default.tsx
  zoo-client/src/app/session-schedule/[id]/page.tsx
  zoo-client/src/app/session-schedule/layout.tsx
  zoo-client/src/components/common/card/CardContent.tsx
  zoo-client/src/components/common/modal/AlertModal.tsx
  zoo-client/src/components/common/modal/InsightInfoModal.tsx
  zoo-client/src/components/common/modal/InterestModal.tsx
  zoo-client/src/components/common/modal/JobModal.tsx
  zoo-client/src/components/common/modal/Layout/ModalHeader.tsx
  zoo-client/src/components/common/modal/SessionApplyModal.tsx
  zoo-client/src/components/common/modal/SessionDetailModal.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/insight/information/InsightContent.tsx
  zoo-client/src/components/insight/information/InsightHeader.tsx
  zoo-client/src/components/insight/information/LikeToggle.tsx
  zoo-client/src/components/insight/information/Profile.tsx
  zoo-client/src/components/insight/information/SocialList.tsx
  zoo-client/src/components/insight/information/reply/ReplyEdit.tsx
  zoo-client/src/components/insight/information/reply/ReplyItem.tsx
  zoo-client/src/components/insight/information/reply/ReplyView.tsx
  zoo-client/src/mock/chip.ts
  zoo-client/src/mock/insight-info.ts
  zoo-client/src/mock/insightChip.ts
  zoo-client/src/mock/sessionsDetailed.ts
  zoo-client/src/types/insight/insight.ts
  zoo-client/src/types/modal/modal.ts
  zoo-client/src/types/session/session.ts
Labels: ✨ FEAT

#47 feat: 인사이트 노트 목록 페이지 UI 구현
  zoo-client/next.config.ts
  zoo-client/public/avatar/Ellipse.svg
  zoo-client/public/radio/thumbnail.svg
  zoo-client/src/actions/session.ts
  zoo-client/src/app/globals.css
  zoo-client/src/app/insight/page.tsx
  zoo-client/src/app/insights/[id]/page.tsx
  zoo-client/src/app/insights/page.tsx
  zoo-client/src/components/common/badge/InterestBadge.tsx
  zoo-client/src/components/common/card/InsightCard.general.tsx
  zoo-client/src/components/common/card/InsightCard.popular.tsx
  zoo-client/src/components/common/profile/CardProfile.tsx
  zoo-client/src/components/common/tab/insight/InsightNoteTab.tsx
  zoo-client/src/components/common/tab/insight/InsightTab.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/insight/information/LikeToggle.tsx
  zoo-client/src/components/insight/information/Profile.tsx
  zoo-client/src/mock/insightList.ts
  zoo-client/src/services/api.ts
  zoo-client/src/services/session.ts
  zoo-client/src/store/common/insight/useInsightNoteTabStore.ts
  zoo-client/src/types/insight/insightCard.ts
  zoo-client/src/types/insight/insightTab.ts
Labels: ✨ FEAT

#52 feat: 인사이트 목록 디자인 변경 및 API 연동
  zoo-client/next.config.ts
  zoo-client/public/button/arrow-up-right.svg
  zoo-client/public/comment/comment.svg
  zoo-client/src/app/globals.css
  zoo-client/src/app/insight-notes/page.tsx
  zoo-client/src/components/common/badge/InterestBadge.tsx
  zoo-client/src/components/common/card/InsightCard.general.tsx
  zoo-client/src/components/common/card/InsightCard.popular.tsx
  zoo-client/src/components/common/card/InsightCard.tsx
  zoo-client/src/components/common/comment/CommentCount.tsx
  zoo-client/src/components/common/profile/CardProfile.tsx
  zoo-client/src/components/common/toggle/LikeToggle.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/insight/information/Profile.tsx
  zoo-client/src/components/insight/insightNotes/GeneralInsightSection.tsx
  zoo-client/src/components/insight/insightNotes/PopularInsightSection.tsx
  zoo-client/src/components/insight/insightNotes/TitleSection.tsx
  zoo-client/src/components/insight/insightNotes/TopSection.tsx
  zoo-client/src/components/insight/insightNotes/index.ts
  zoo-client/src/components/insight/note/NoteItem.tsx
  zoo-client/src/constants/insights.ts
  zoo-client/src/hook/common/useObserver.ts
  zoo-client/src/hook/insights/insight.ts
  zoo-client/src/mock/insightList.ts
  zoo-client/src/services/insight.ts
  zoo-client/src/styles/tokens/colors.ts
  zoo-client/src/types/insight/enum/insights.ts
  zoo-client/src/types/insight/insightCard.ts
  zoo-client/src/utils/insightDate.ts
Labels: ✨ FEAT

#58 feat: 비회원 로그인 API 연동
  zoo-client/middleware.ts
  zoo-client/src/app/insight-notes/page.tsx
  zoo-client/src/components/common/PrivatedRouter.tsx
  zoo-client/src/components/common/navigationBar/NavigationBar.tsx
  zoo-client/src/components/common/textField/TextField.tsx
  zoo-client/src/components/insight/insightNotes/GeneralInsightSection.tsx
  zoo-client/src/components/insight/insightNotes/LoginModal.tsx
  zoo-client/src/components/insight/insightNotes/index.ts
  zoo-client/src/components/noneMember/NoneMemberForm.tsx
  zoo-client/src/hooks/common/useTimer.ts
  zoo-client/src/services/auth.ts
  zoo-client/src/services/insight.ts
  zoo-client/src/store/common/auth/useAuthStore.ts
  zoo-client/tailwind.config.ts
Labels: ✨ FEAT

#62 feat: 마이 페이지 인사이트 UI & API 연동
  zoo-client/src/app/mypage/@content/insights/page.tsx
  zoo-client/src/app/mypage/@content/sessions/[id]/page.tsx
  zoo-client/src/app/mypage/@content/sessions/page.tsx
  zoo-client/src/app/session-apply/page.tsx
  zoo-client/src/app/session-schedule/page.tsx
  zoo-client/src/components/common/modal/SessionDetailModal.tsx
  zoo-client/src/components/common/navigationBar/InsightSideNavigationBar.tsx
  zoo-client/src/components/common/navigationBar/NavigationBar.tsx
  zoo-client/src/components/common/profile/CardProfile.tsx
  zoo-client/src/components/common/tab/Tab.tsx
  zoo-client/src/components/insight/insightNotes/GeneralInsightSection.tsx
  zoo-client/src/components/insight/note/NoteItem.tsx
  zoo-client/src/hooks/insights/useInsights.ts
  zoo-client/src/services/insight.ts
  zoo-client/src/types/insight/insightNote.ts
  zoo-client/src/utils/insightDate.ts
Labels: ✨ FEAT

#64 feat: 사용자 설정 페이지 UI 구현 및 API 연동
  zoo-client/src/app/globals.css
  zoo-client/src/app/mypage/@content/page.tsx
  zoo-client/src/components/common/contentAgree/ContentAgree.tsx
  zoo-client/src/components/common/navigationBar/NavigationBar.tsx
  zoo-client/src/components/common/textField/TextField.tsx
  zoo-client/src/components/common/textField/UserLabel.tsx
  zoo-client/src/components/index.ts
  zoo-client/src/components/mypage/UserProfile.tsx
  zoo-client/src/components/mypage/UserProfileForm.tsx
  zoo-client/src/constants/messages.ts
  zoo-client/src/hooks/profile/useProfile.tsx
  zoo-client/src/services/auth.ts
  zoo-client/src/services/profile.ts
Labels: ✨ FEAT
